{
 "title": "Smart Supermarket",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Price Values",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  node_id AS metric,\n  current_price\nFROM price_display_state\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Weight Values",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  node_id AS metric,\n  current_weight\nFROM weight_sensor_state\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fridge Temperature Node Values",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  node_id AS metric,\n  temperature,\n  desired_temp\nFROM fridge_temperatures\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Fridge Alarm Sensor",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  state AS metric,\n  ID\nFROM fridge_alarm_light\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}